"""auto

Revision ID: 1b665188447d
Revises: a1b2c3d4e5f6
Create Date: 2026-07-03 15:42:31.978505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b665188447d'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('environment_variables', 'type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('STRING', 'NUMBER', 'BOOLEAN', 'JSON', name='variable_type', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'STRING'::character varying"))
    op.create_foreign_key('fk_env_var_created_by', 'environment_variables', 'users', ['created_by'], ['id'], ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key('fk_env_created_by', 'environments', 'users', ['created_by'], ['id'], ondelete='RESTRICT', use_alter=True)
    op.alter_column('flow_steps', 'action',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.Enum('CLICK', 'DOUBLE_CLICK', 'RIGHT_CLICK', 'TYPE', 'APPEND', 'CLEAR', 'SELECT', 'CHECK', 'UNCHECK', 'HOVER', 'SCROLL_TO', 'WAIT_FOR', 'NAVIGATE', 'SCREENSHOT', 'EXECUTE_SCRIPT', 'DRAG_DROP', 'UPLOAD_FILE', 'PRESS_KEY', 'FLOW', name='step_action', native_enum=False),
               existing_nullable=False)
    op.create_foreign_key('fk_flow_step_created_by', 'flow_steps', 'users', ['created_by'], ['id'], ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key('fk_flow_step_po', 'flow_steps', 'page_objects', ['page_object_id'], ['id'], ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key('fk_flow_created_by', 'flows', 'users', ['created_by'], ['id'], ondelete='RESTRICT', use_alter=True)
    op.add_column('run_events', sa.Column('event_metadata', sa.JSON(), nullable=True))
    op.alter_column('run_events', 'severity',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', name='event_severity', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'INFO'::character varying"))
    op.drop_column('run_events', 'metadata')
    op.create_foreign_key('fk_assertion_po', 'step_assertions', 'page_objects', ['target_page_object_id'], ['id'], ondelete='RESTRICT', use_alter=True)
    op.alter_column('step_results', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('PENDING', 'RUNNING', 'PASSED', 'FAILED', 'SKIPPED', 'OPTIONAL_FAILED', name='step_result_status', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.create_foreign_key('fk_test_case_owner', 'test_cases', 'users', ['owner_user_id'], ['id'], ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key('fk_test_case_app', 'test_cases', 'applications', ['application_id'], ['id'], ondelete='RESTRICT', use_alter=True)
    op.alter_column('test_runs', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('QUEUED', 'DISPATCHED', 'RUNNING', 'COMPLETED', 'FAILED', 'ABORTED', 'CANCELLED', 'TIMED_OUT', name='run_status', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'QUEUED'::character varying"))
    op.alter_column('test_runs', 'priority',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='run_priority', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'NORMAL'::character varying"))
    op.create_foreign_key('fk_run_env', 'test_runs', 'environments', ['environment_id'], ['id'], ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key('fk_run_agent', 'test_runs', 'agents', ['agent_id'], ['id'], ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key('fk_run_triggered_by', 'test_runs', 'users', ['triggered_by'], ['id'], ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key('fk_test_step_po', 'test_steps', 'page_objects', ['page_object_id'], ['id'], ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key('fk_test_suite_owner', 'test_suites', 'users', ['owner_user_id'], ['id'], ondelete='RESTRICT', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_test_suite_owner', 'test_suites', type_='foreignkey')
    op.drop_constraint('fk_test_step_po', 'test_steps', type_='foreignkey')
    op.drop_constraint('fk_run_triggered_by', 'test_runs', type_='foreignkey')
    op.drop_constraint('fk_run_agent', 'test_runs', type_='foreignkey')
    op.drop_constraint('fk_run_env', 'test_runs', type_='foreignkey')
    op.alter_column('test_runs', 'priority',
               existing_type=sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='run_priority', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'NORMAL'::character varying"))
    op.alter_column('test_runs', 'status',
               existing_type=sa.Enum('QUEUED', 'DISPATCHED', 'RUNNING', 'COMPLETED', 'FAILED', 'ABORTED', 'CANCELLED', 'TIMED_OUT', name='run_status', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'QUEUED'::character varying"))
    op.drop_constraint('fk_test_case_app', 'test_cases', type_='foreignkey')
    op.drop_constraint('fk_test_case_owner', 'test_cases', type_='foreignkey')
    op.alter_column('step_results', 'status',
               existing_type=sa.Enum('PENDING', 'RUNNING', 'PASSED', 'FAILED', 'SKIPPED', 'OPTIONAL_FAILED', name='step_result_status', native_enum=False),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.drop_constraint('fk_assertion_po', 'step_assertions', type_='foreignkey')
    op.add_column('run_events', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('run_events', 'severity',
               existing_type=sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', name='event_severity', native_enum=False),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'INFO'::character varying"))
    op.drop_column('run_events', 'event_metadata')
    op.drop_constraint('fk_flow_created_by', 'flows', type_='foreignkey')
    op.drop_constraint('fk_flow_step_po', 'flow_steps', type_='foreignkey')
    op.drop_constraint('fk_flow_step_created_by', 'flow_steps', type_='foreignkey')
    op.alter_column('flow_steps', 'action',
               existing_type=sa.Enum('CLICK', 'DOUBLE_CLICK', 'RIGHT_CLICK', 'TYPE', 'APPEND', 'CLEAR', 'SELECT', 'CHECK', 'UNCHECK', 'HOVER', 'SCROLL_TO', 'WAIT_FOR', 'NAVIGATE', 'SCREENSHOT', 'EXECUTE_SCRIPT', 'DRAG_DROP', 'UPLOAD_FILE', 'PRESS_KEY', 'FLOW', name='step_action', native_enum=False),
               type_=sa.VARCHAR(length=60),
               existing_nullable=False)
    op.drop_constraint('fk_env_created_by', 'environments', type_='foreignkey')
    op.drop_constraint('fk_env_var_created_by', 'environment_variables', type_='foreignkey')
    op.alter_column('environment_variables', 'type',
               existing_type=sa.Enum('STRING', 'NUMBER', 'BOOLEAN', 'JSON', name='variable_type', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'STRING'::character varying"))
    # ### end Alembic commands ###
