"""phase1_object_repository

Revision ID: 6d08828d23b5
Revises: f61544fc9795
Create Date: 2026-06-05 11:34:16.500978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d08828d23b5'
down_revision: Union[str, None] = 'f61544fc9795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('owner_team', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name='fk_application_owner', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_applications_org_name')
    )
    op.create_index('idx_applications_org_deleted', 'applications', ['org_id', 'deleted_at'], unique=False)
    op.create_index('idx_applications_org_id', 'applications', ['org_id'], unique=False)
    op.create_index('idx_applications_org_status', 'applications', ['org_id', 'status'], unique=False)
    op.create_table('modules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('owner_team', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name='fk_module_owner', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'application_id', 'name', name='uq_modules_org_app_name')
    )
    op.create_index('idx_modules_application', 'modules', ['application_id'], unique=False)
    op.create_index('idx_modules_org_app_deleted', 'modules', ['org_id', 'application_id', 'deleted_at'], unique=False)
    op.create_index('idx_modules_org_deleted', 'modules', ['org_id', 'deleted_at'], unique=False)
    op.create_index('idx_modules_org_id', 'modules', ['org_id'], unique=False)
    op.create_table('pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url_pattern', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('owner_team', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name='fk_page_owner', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'module_id', 'name', name='uq_pages_org_module_name')
    )
    op.create_index('idx_pages_module', 'pages', ['module_id'], unique=False)
    op.create_index('idx_pages_org_deleted', 'pages', ['org_id', 'deleted_at'], unique=False)
    op.create_index('idx_pages_org_id', 'pages', ['org_id'], unique=False)
    op.create_index('idx_pages_org_mod_deleted', 'pages', ['org_id', 'module_id', 'deleted_at'], unique=False)
    op.create_table('page_objects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('object_type', sa.String(length=30), nullable=False),
    sa.Column('page_area', sa.String(length=30), nullable=True),
    sa.Column('criticality', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('locators', sa.JSON(), nullable=True),
    sa.Column('search_keywords', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('owner_team', sa.String(length=100), nullable=True),
    sa.Column('last_validated_at', sa.DateTime(), nullable=True),
    sa.Column('last_validated_by', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['last_validated_by'], ['users.id'], name='fk_page_object_validator', use_alter=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name='fk_page_object_owner', use_alter=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'page_id', 'name', name='uq_page_objects_org_page_name')
    )
    op.create_index('idx_page_objects_criticality', 'page_objects', ['org_id', 'criticality'], unique=False)
    op.create_index('idx_page_objects_org_deleted', 'page_objects', ['org_id', 'deleted_at'], unique=False)
    op.create_index('idx_page_objects_org_id', 'page_objects', ['org_id'], unique=False)
    op.create_index('idx_page_objects_page', 'page_objects', ['page_id'], unique=False)
    op.create_index('idx_page_objects_status', 'page_objects', ['org_id', 'status'], unique=False)
    op.create_table('page_object_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('page_object_id', sa.UUID(), nullable=False),
    sa.Column('storage_provider', sa.String(length=30), nullable=False),
    sa.Column('object_key', sa.String(length=1000), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('page_snapshot_provider', sa.String(length=30), nullable=True),
    sa.Column('page_snapshot_key', sa.String(length=1000), nullable=True),
    sa.Column('bounding_box', sa.JSON(), nullable=True),
    sa.Column('captured_by', sa.UUID(), nullable=True),
    sa.Column('capture_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['captured_by'], ['users.id'], name='fk_snapshot_captured_by', use_alter=True),
    sa.ForeignKeyConstraint(['page_object_id'], ['page_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_po_snapshots_org', 'page_object_snapshots', ['org_id'], unique=False)
    op.create_index('idx_po_snapshots_page_object', 'page_object_snapshots', ['page_object_id'], unique=False)
    op.create_foreign_key('fk_org_deleted_by', 'organizations', 'users', ['deleted_by'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_org_deleted_by', 'organizations', type_='foreignkey')
    op.drop_index('idx_po_snapshots_page_object', table_name='page_object_snapshots')
    op.drop_index('idx_po_snapshots_org', table_name='page_object_snapshots')
    op.drop_table('page_object_snapshots')
    op.drop_index('idx_page_objects_status', table_name='page_objects')
    op.drop_index('idx_page_objects_page', table_name='page_objects')
    op.drop_index('idx_page_objects_org_id', table_name='page_objects')
    op.drop_index('idx_page_objects_org_deleted', table_name='page_objects')
    op.drop_index('idx_page_objects_criticality', table_name='page_objects')
    op.drop_table('page_objects')
    op.drop_index('idx_pages_org_mod_deleted', table_name='pages')
    op.drop_index('idx_pages_org_id', table_name='pages')
    op.drop_index('idx_pages_org_deleted', table_name='pages')
    op.drop_index('idx_pages_module', table_name='pages')
    op.drop_table('pages')
    op.drop_index('idx_modules_org_id', table_name='modules')
    op.drop_index('idx_modules_org_deleted', table_name='modules')
    op.drop_index('idx_modules_org_app_deleted', table_name='modules')
    op.drop_index('idx_modules_application', table_name='modules')
    op.drop_table('modules')
    op.drop_index('idx_applications_org_status', table_name='applications')
    op.drop_index('idx_applications_org_id', table_name='applications')
    op.drop_index('idx_applications_org_deleted', table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
