"""phase2_test_case_management

Revision ID: 9aa74c286b25
Revises: 6d08828d23b5
Create Date: 2026-06-16 19:10:26.421615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aa74c286b25'
down_revision: Union[str, None] = '6d08828d23b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_suites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='suite_status', native_enum=False), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('owner_team', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name='fk_test_suite_owner', ondelete='RESTRICT', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_test_suites_org_name')
    )
    op.create_index('idx_test_suites_org_deleted', 'test_suites', ['org_id', 'deleted_at'], unique=False)
    op.create_index('idx_test_suites_org_id', 'test_suites', ['org_id'], unique=False)
    op.create_index('idx_test_suites_org_status', 'test_suites', ['org_id', 'status'], unique=False)
    op.create_table('test_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('suite_id', sa.UUID(), nullable=True),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='test_priority', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'READY', 'BLOCKED', 'DEPRECATED', name='test_status', native_enum=False), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('estimated_duration_secs', sa.Integer(), nullable=True),
    sa.Column('preconditions', sa.Text(), nullable=True),
    sa.Column('postconditions', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('owner_team', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('version >= 1', name='ck_test_cases_version_positive'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name='fk_test_case_app', ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name='fk_test_case_owner', ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['suite_id'], ['test_suites.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('suite_id', 'name', name='uq_test_cases_suite_name')
    )
    op.create_index('idx_test_cases_org_app', 'test_cases', ['org_id', 'application_id'], unique=False)
    op.create_index('idx_test_cases_org_deleted', 'test_cases', ['org_id', 'deleted_at'], unique=False)
    op.create_index('idx_test_cases_org_id', 'test_cases', ['org_id'], unique=False)
    op.create_index('idx_test_cases_org_priority', 'test_cases', ['org_id', 'priority'], unique=False)
    op.create_index('idx_test_cases_org_status', 'test_cases', ['org_id', 'status'], unique=False)
    op.create_index('idx_test_cases_org_suite', 'test_cases', ['org_id', 'suite_id'], unique=False)
    op.create_table('test_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('test_case_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('CLICK', 'DOUBLE_CLICK', 'RIGHT_CLICK', 'TYPE', 'APPEND', 'CLEAR', 'SELECT', 'CHECK', 'UNCHECK', 'HOVER', 'SCROLL_TO', 'WAIT_FOR', 'NAVIGATE', 'SCREENSHOT', 'EXECUTE_SCRIPT', 'DRAG_DROP', 'UPLOAD_FILE', 'PRESS_KEY', name='step_action', native_enum=False), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('page_object_id', sa.UUID(), nullable=True),
    sa.Column('input_value', sa.Text(), nullable=True),
    sa.Column('target_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('timeout_ms', sa.Integer(), nullable=False),
    sa.Column('screenshot_on_failure', sa.Boolean(), nullable=False),
    sa.Column('execution_hint', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('position >= 1', name='ck_test_steps_position_positive'),
    sa.CheckConstraint('version >= 1', name='ck_test_steps_version_positive'),
    sa.ForeignKeyConstraint(['page_object_id'], ['page_objects.id'], name='fk_test_step_po', ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_test_steps_case', 'test_steps', ['test_case_id'], unique=False)
    op.create_index('idx_test_steps_case_position', 'test_steps', ['test_case_id', 'position'], unique=False)
    op.create_index('idx_test_steps_org', 'test_steps', ['org_id'], unique=False)
    op.create_index('idx_test_steps_page_object', 'test_steps', ['page_object_id'], unique=False)
    op.create_index(
        'uix_test_steps_case_position_live', 'test_steps', ['test_case_id', 'position'],
        unique=True,
        # NOTE: postgresql_where= is a PostgreSQL-only dialect hint.
        # On SQLite (used by the test suite) this argument is silently ignored,
        # so the index becomes a full (non-partial) unique constraint.
        # On PostgreSQL (production) the partial condition is enforced correctly.
        postgresql_where='deleted_at IS NULL',
    )
    op.create_table('step_assertions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('assertion_type', sa.Enum('VISIBLE', 'NOT_VISIBLE', 'TEXT_EQUALS', 'TEXT_CONTAINS', 'TEXT_MATCHES', 'VALUE_EQUALS', 'ATTRIBUTE_EQUALS', 'URL_EQUALS', 'URL_CONTAINS', 'TITLE_EQUALS', 'ELEMENT_COUNT', 'ENABLED', 'DISABLED', 'CHECKED', 'UNCHECKED', name='assertion_type_enum', native_enum=False), nullable=False),
    sa.Column('target_page_object_id', sa.UUID(), nullable=True),
    sa.Column('expected_value', sa.Text(), nullable=True),
    sa.Column('attribute_name', sa.String(length=100), nullable=True),
    sa.Column('is_negated', sa.Boolean(), nullable=False),
    sa.Column('is_fatal', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('position >= 1', name='ck_step_assertions_position_positive'),
    sa.ForeignKeyConstraint(['step_id'], ['test_steps.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_page_object_id'], ['page_objects.id'], name='fk_assertion_po', ondelete='RESTRICT', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_step_assertions_org', 'step_assertions', ['org_id'], unique=False)
    op.create_index('idx_step_assertions_page_object', 'step_assertions', ['target_page_object_id'], unique=False)
    op.create_index('idx_step_assertions_step', 'step_assertions', ['step_id'], unique=False)
    op.create_index(
        'uix_step_assertions_step_pos_live', 'step_assertions', ['step_id', 'position'],
        unique=True,
        # NOTE: postgresql_where= is a PostgreSQL-only dialect hint.
        # On SQLite this argument is silently ignored (non-partial unique constraint).
        # On PostgreSQL (production) the partial condition is enforced correctly.
        postgresql_where='deleted_at IS NULL',
    )
    op.create_foreign_key('fk_application_owner', 'applications', 'users', ['owner_user_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_module_owner', 'modules', 'users', ['owner_user_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_snapshot_captured_by', 'page_object_snapshots', 'users', ['captured_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_page_object_owner', 'page_objects', 'users', ['owner_user_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_page_object_validator', 'page_objects', 'users', ['last_validated_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_page_owner', 'pages', 'users', ['owner_user_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_page_owner', 'pages', type_='foreignkey')
    op.drop_constraint('fk_page_object_validator', 'page_objects', type_='foreignkey')
    op.drop_constraint('fk_page_object_owner', 'page_objects', type_='foreignkey')
    op.drop_constraint('fk_snapshot_captured_by', 'page_object_snapshots', type_='foreignkey')
    op.drop_constraint('fk_module_owner', 'modules', type_='foreignkey')
    op.drop_constraint('fk_application_owner', 'applications', type_='foreignkey')
    op.drop_index('uix_step_assertions_step_pos_live', table_name='step_assertions', postgresql_where='deleted_at IS NULL')
    op.drop_index('idx_step_assertions_step', table_name='step_assertions')
    op.drop_index('idx_step_assertions_page_object', table_name='step_assertions')
    op.drop_index('idx_step_assertions_org', table_name='step_assertions')
    op.drop_table('step_assertions')
    op.drop_index('uix_test_steps_case_position_live', table_name='test_steps', postgresql_where='deleted_at IS NULL')
    op.drop_index('idx_test_steps_page_object', table_name='test_steps')
    op.drop_index('idx_test_steps_org', table_name='test_steps')
    op.drop_index('idx_test_steps_case_position', table_name='test_steps')
    op.drop_index('idx_test_steps_case', table_name='test_steps')
    op.drop_table('test_steps')
    op.drop_index('idx_test_cases_org_suite', table_name='test_cases')
    op.drop_index('idx_test_cases_org_status', table_name='test_cases')
    op.drop_index('idx_test_cases_org_priority', table_name='test_cases')
    op.drop_index('idx_test_cases_org_id', table_name='test_cases')
    op.drop_index('idx_test_cases_org_deleted', table_name='test_cases')
    op.drop_index('idx_test_cases_org_app', table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_index('idx_test_suites_org_status', table_name='test_suites')
    op.drop_index('idx_test_suites_org_id', table_name='test_suites')
    op.drop_index('idx_test_suites_org_deleted', table_name='test_suites')
    op.drop_table('test_suites')
    # ### end Alembic commands ###
