"""phase0_foundation

Revision ID: f61544fc9795
Revises: None
Create Date: 2026-06-03 19:37:41.219623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f61544fc9795'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_revisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.String(length=100), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('change_summary', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_revisions_asset', 'asset_revisions', ['asset_type', 'asset_id'], unique=False)
    op.create_index('idx_revisions_org', 'asset_revisions', ['org_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('revision_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_actor', 'audit_events', ['actor_id'], unique=False)
    op.create_index('idx_audit_org_entity', 'audit_events', ['org_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_org_timestamp', 'audit_events', ['org_id', 'timestamp'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='fk_org_deleted_by', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_organizations_slug', 'organizations', ['slug'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_roles_org', 'roles', ['org_id'], unique=False)
    op.create_table('webhooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('target_url', sa.String(length=500), nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_webhooks_org', 'webhooks', ['org_id'], unique=False)
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('os_version', sa.String(length=100), nullable=True),
    sa.Column('agent_version', sa.String(length=50), nullable=True),
    sa.Column('protocol_version', sa.Integer(), nullable=True),
    sa.Column('payload_versions_supported', sa.JSON(), nullable=True),
    sa.Column('browser_versions', sa.JSON(), nullable=True),
    sa.Column('installed_apps', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('host_info', sa.JSON(), nullable=True),
    sa.Column('max_parallel_sessions', sa.Integer(), nullable=False),
    sa.Column('current_parallel_sessions', sa.Integer(), nullable=False),
    sa.Column('last_capacity_update', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agents_org_deleted', 'agents', ['org_id', 'deleted_at'], unique=False)
    op.create_index('idx_agents_org_id', 'agents', ['org_id'], unique=False)
    op.create_index('idx_agents_org_status', 'agents', ['org_id', 'status'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_org_deleted', 'users', ['org_id', 'deleted_at'], unique=False)
    op.create_index('idx_users_org_id', 'users', ['org_id'], unique=False)
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    op.create_table('agent_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('session_log_path', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_sessions_agent', 'agent_sessions', ['agent_id'], unique=False)
    op.create_index('idx_agent_sessions_execution', 'agent_sessions', ['execution_id'], unique=False)
    op.create_index('idx_agent_sessions_org', 'agent_sessions', ['org_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_org', 'notifications', ['org_id'], unique=False)
    op.create_index('idx_notifications_unread', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index('idx_notifications_user', 'notifications', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_index('idx_user_roles_user', 'user_roles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_roles_user', table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index('idx_notifications_user', table_name='notifications')
    op.drop_index('idx_notifications_unread', table_name='notifications')
    op.drop_index('idx_notifications_org', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_agent_sessions_org', table_name='agent_sessions')
    op.drop_index('idx_agent_sessions_execution', table_name='agent_sessions')
    op.drop_index('idx_agent_sessions_agent', table_name='agent_sessions')
    op.drop_table('agent_sessions')
    op.drop_index('idx_users_username', table_name='users')
    op.drop_index('idx_users_org_id', table_name='users')
    op.drop_index('idx_users_org_deleted', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_index('idx_agents_org_status', table_name='agents')
    op.drop_index('idx_agents_org_id', table_name='agents')
    op.drop_index('idx_agents_org_deleted', table_name='agents')
    op.drop_table('agents')
    op.drop_index('idx_webhooks_org', table_name='webhooks')
    op.drop_table('webhooks')
    op.drop_index('idx_roles_org', table_name='roles')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_index('idx_organizations_slug', table_name='organizations')
    op.drop_table('organizations')
    op.drop_index('idx_audit_org_timestamp', table_name='audit_events')
    op.drop_index('idx_audit_org_entity', table_name='audit_events')
    op.drop_index('idx_audit_actor', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('idx_revisions_org', table_name='asset_revisions')
    op.drop_index('idx_revisions_asset', table_name='asset_revisions')
    op.drop_table('asset_revisions')
    # ### end Alembic commands ###
